#include "data_acquisition.hpp"
#include "main.h" // generated by CubeMX
#include <cstring> // for memset

// External handles from CubeMX (these will be generated by CubeMX)
extern I2S_HandleTypeDef hi2s2;
extern DMA_HandleTypeDef hdma_i2s2_ext_rx;

// DMA buffer for circular mode (single buffer with half/full callbacks)
static int16_t dmaBuffer[DMA_BUFFER_SIZE];


// Alternative: True double buffering (commented out for now)
// static int16_t dmaBufferA[DMA_BUFFER_SIZE];
// static int16_t dmaBufferB[DMA_BUFFER_SIZE];

// Control flags
volatile bool bufferAReady = false;
volatile bool bufferBReady = false;
volatile bool acquisitionActive = false;
volatile AcquisitionStatus_t acquisitionStatus = ACQUISITION_OK;

// Frame buffer for processed data
static int16_t frameBuffer[TOTAL_SAMPLES_PER_FRAME];
static bool frameReady = false;

// Statistics
static uint32_t framesCaptured = 0;
static uint32_t overrunCount = 0;

AcquisitionStatus_t Audio_InitAcquisition(void)
{
    // Reset all flags and counters
    bufferAReady = false;
    bufferBReady = false;
    acquisitionActive = false;
    frameReady = false;
    framesCaptured = 0;
    overrunCount = 0;
    
    // Clear buffers
    memset(dmaBuffer, 0, sizeof(dmaBuffer));
    // Alternative: Clear both buffers for true double buffering
    // memset(dmaBufferA, 0, sizeof(dmaBufferA));
    // memset(dmaBufferB, 0, sizeof(dmaBufferB));
    memset(frameBuffer, 0, sizeof(frameBuffer));
    
    // Initialize I2S peripheral (CubeMX handles basic config)
    if (HAL_I2S_Init(&hi2s2) != HAL_OK) {
        acquisitionStatus = ACQUISITION_ERROR;
        return ACQUISITION_ERROR;
    }
    
    acquisitionStatus = ACQUISITION_OK;
    return ACQUISITION_OK;
}

AcquisitionStatus_t Audio_StartAcquisition(void)
{
    if (acquisitionActive) {
        return ACQUISITION_BUSY;
    }
    
    // Start DMA in circular mode (single buffer with half/full callbacks)
    // Note: Configure DMA in circular mode in CubeMX for this to work properly
    if (HAL_I2S_Receive_DMA(&hi2s2, (uint16_t*)dmaBuffer, DMA_BUFFER_SIZE) != HAL_OK) {
        acquisitionStatus = ACQUISITION_ERROR;
        return ACQUISITION_ERROR;
    }
    
    // Alternative: True double buffering approach (commented out)
    // if (HAL_I2S_Receive_DMA(&hi2s2, (uint16_t*)dmaBufferA, DMA_BUFFER_SIZE) != HAL_OK) {
    //     acquisitionStatus = ACQUISITION_ERROR;
    //     return ACQUISITION_ERROR;
    // }
    
    acquisitionActive = true;
    acquisitionStatus = ACQUISITION_OK;
    return ACQUISITION_OK;
}

AcquisitionStatus_t Audio_StopAcquisition(void)
{
    if (!acquisitionActive) {
        return ACQUISITION_OK;
    }
    
    // Stop DMA transfer
    if (HAL_I2S_DMAStop(&hi2s2) != HAL_OK) {
        acquisitionStatus = ACQUISITION_ERROR;
        return ACQUISITION_ERROR;
    }
    
    acquisitionActive = false;
    acquisitionStatus = ACQUISITION_OK;
    return ACQUISITION_OK;
}

bool Audio_GetFrame(int16_t *destBuffer)
{
    if (!frameReady || destBuffer == NULL) {
        return false;
    }
    
    // Copy frame data
    memcpy(destBuffer, frameBuffer, sizeof(frameBuffer));
    frameReady = false;
    framesCaptured++;
    
    return true;
}

bool Audio_IsDataReady(void)
{
    return frameReady;
}

void Audio_ClearDataReady(void)
{
    frameReady = false;
}

uint32_t Audio_GetSampleRate(void)
{
    return SAMPLE_RATE_HZ;
}

uint16_t Audio_GetChannelCount(void)
{
    return MIC_ARRAY_SIZE;
}

void HAL_I2S_RxHalfCpltCallback(I2S_HandleTypeDef *hi2s)
{
    if (hi2s->Instance == SPI2 && acquisitionActive) {
        bufferAReady = true;
        
        // Process first half of circular buffer
        if (!frameReady) {
            memcpy(frameBuffer, dmaBuffer, sizeof(frameBuffer));
            frameReady = true;
        } else {
            overrunCount++; // Data overrun
        }
    }
}

void HAL_I2S_RxCpltCallback(I2S_HandleTypeDef *hi2s)
{
    if (hi2s->Instance == SPI2 && acquisitionActive) {
        bufferBReady = true;
        
        // Process second half of circular buffer
        if (!frameReady) {
            memcpy(frameBuffer, &dmaBuffer[DMA_BUFFER_SIZE/2], sizeof(frameBuffer));
            frameReady = true;
        } else {
            overrunCount++; // Data overrun
        }
        
        // Alternative: True double buffering approach (commented out)
        // memcpy(frameBuffer, dmaBufferB, sizeof(frameBuffer));
    }
}

void HAL_I2S_ErrorCallback(I2S_HandleTypeDef *hi2s)
{
    if (hi2s->Instance == SPI2) {
        acquisitionStatus = ACQUISITION_ERROR;
        Audio_ErrorHandler();
    }
}

void Audio_ErrorHandler(void)
{
    // Stop acquisition
    Audio_StopAcquisition();
    
    // Reset flags
    bufferAReady = false;
    bufferBReady = false;
    frameReady = false;
    
    // Could add LED indication or other error handling here
}
