#include "data_acquisition.hpp"
#include <stdint.h>
#include <cstring> // for memset
#include "main.h" // generated by CubeMX
#include "spi.h"  // SPI3 configuration

// External handles from CubeMX (these will be generated by CubeMX)
extern SPI_HandleTypeDef hspi3;
extern DMA_HandleTypeDef hdma_spi3_rx;

// DMA buffer for circular mode (single buffer with half/full callbacks)
static int16_t dmaBuffer[DMA_BUFFER_SIZE];

// Control flags
volatile bool bufferAReady = false;
volatile bool bufferBReady = false;
volatile bool acquisitionActive = false;
volatile AcquisitionStatus_t acquisitionStatus = ACQUISITION_OK;

// Frame buffer for processed data
static int16_t frameBuffer[TOTAL_SAMPLES_PER_FRAME];
static bool frameReady = false;

// Statistics
static unsigned int framesCaptured = 0;
static unsigned int overrunCount = 0;

AcquisitionStatus_t Audio_InitAcquisition(void)
{
    // Reset all flags and counters
    bufferAReady = false;
    bufferBReady = false;
    acquisitionActive = false;
    frameReady = false;
    framesCaptured = 0;
    overrunCount = 0;
    
    // Clear buffers
    memset(dmaBuffer, 0, sizeof(dmaBuffer));
    memset(frameBuffer, 0, sizeof(frameBuffer));
    
    // Initialize SPI3 peripheral in I2S mode (CubeMX handles basic config)
    if (HAL_SPI_Init(&hspi3) != HAL_OK) {
        acquisitionStatus = ACQUISITION_ERROR;
        return ACQUISITION_ERROR;
    }
    
    acquisitionStatus = ACQUISITION_OK;
    return ACQUISITION_OK;
}

AcquisitionStatus_t Audio_StartAcquisition(void)
{
    if (acquisitionActive) {
        return ACQUISITION_BUSY;
    }
    
    // Start DMA in circular mode (single buffer with half/full callbacks)
    // Note: Configure DMA in circular mode in CubeMX for this to work properly
    if (HAL_SPI_Receive_DMA(&hspi3, (uint8_t*)dmaBuffer, DMA_BUFFER_SIZE * 2) != HAL_OK) {
        acquisitionStatus = ACQUISITION_ERROR;
        return ACQUISITION_ERROR;
    }
    
    acquisitionActive = true;
    acquisitionStatus = ACQUISITION_OK;
    return ACQUISITION_OK;
}

AcquisitionStatus_t Audio_StopAcquisition(void)
{
    if (!acquisitionActive) {
        return ACQUISITION_OK;
    }
    
    // Stop DMA transfer
    if (HAL_SPI_DMAStop(&hspi3) != HAL_OK) {
        acquisitionStatus = ACQUISITION_ERROR;
        return ACQUISITION_ERROR;
    }
    
    acquisitionActive = false;
    acquisitionStatus = ACQUISITION_OK;
    return ACQUISITION_OK;
}

bool Audio_GetFrame(int16_t *destBuffer)
{
    if (!frameReady || destBuffer == NULL) {
        return false;
    }
    
    // Copy frame data
    memcpy(destBuffer, frameBuffer, sizeof(frameBuffer));
    frameReady = false;
    framesCaptured++;
    
    return true;
}

bool Audio_IsDataReady(void)
{
    return frameReady;
}

void Audio_ClearDataReady(void)
{
    frameReady = false;
}

unsigned int Audio_GetSampleRate(void)
{
    return SAMPLE_RATE_HZ;
}

uint16_t Audio_GetChannelCount(void)
{
    return MIC_ARRAY_SIZE;
}

void HAL_SPI_RxHalfCpltCallback(SPI_HandleTypeDef *hspi)
{
    if (hspi == &hspi3 && acquisitionActive) {
        bufferAReady = true;
        
        // Process first half of circular buffer
        if (!frameReady) {
            memcpy(frameBuffer, dmaBuffer, sizeof(frameBuffer));
            frameReady = true;
        } else {
            overrunCount++; // Data overrun
        }
    }
}

void HAL_SPI_RxCpltCallback(SPI_HandleTypeDef *hspi)
{
    if (hspi == &hspi3 && acquisitionActive) {
        bufferBReady = true;
        
        // Process second half of circular buffer
        if (!frameReady) {
            memcpy(frameBuffer, &dmaBuffer[DMA_BUFFER_SIZE/2], sizeof(frameBuffer));
            frameReady = true;
        } else {
            overrunCount++; // Data overrun
        }
    }
}

void HAL_SPI_ErrorCallback(SPI_HandleTypeDef *hspi)
{
    if (hspi == &hspi3) {
        acquisitionStatus = ACQUISITION_ERROR;
        Audio_ErrorHandler();
    }
}

void Audio_ErrorHandler(void)
{
    // Stop acquisition
    Audio_StopAcquisition();
    
    // Reset flags
    bufferAReady = false;
    bufferBReady = false;
    frameReady = false;
    
    // Could add LED indication or other error handling here
}
