; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:stm32g473vctx]
platform = ststm32
board = stm32g473vctx
framework = stm32cube
board_build.mcu = stm32g473vctx
board_build.f_cpu = 170000000L
board_build.fpu = fpv4-sp-d16
board_build.float-abi = hard
build_type = release
build_flags = 
    -g3 
    -Og

    -mfpu=fpv4-sp-d16
    -mfloat-abi=hard
    -I src/
    -I src/CubeMX/Core/Inc
    -I src/CubeMX/Drivers/CMSIS/DSP/Include
    -I src/CubeMX/USB_Device/App
    -I src/CubeMX/USB_Device/Target


    ; ---- Link the prebuilt CMSIS-DSP library (.a) ----
    -L src/CubeMX/Drivers/CMSIS/DSP/Lib/GCC
    -l arm_cortexM4lf_math

debug_tool = stlink
upload_protocol = stlink
debug_load_mode = always

monitor_speed = 115200
build_src_filter = 
    +<*> 
    -<CubeMX/Drivers/CMSIS/DSP/>
    -<CubeMX/Drivers/CMSIS/NN/>


extra_scripts = pre:force_fpu.py
